on:
  pull_request:
  merge_group:

name: Execution checks

jobs:
  test-utils:
    name: Test utility programs
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get -y update
      - run: sudo apt-get -y install python3 python3-yaml
      - run: python3 misc/gen_dependencies --test
      - run: python3 misc/gen_deployment --test

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get -y update
      - run: sudo apt -y install build-essential mtools perl libxml-libxml-perl libxml-simple-perl libfile-copy-recursive-perl bc python3 python3-venv qemu-system-x86 clang
      - run: make configure
      - run: python -mvenv venv
      - run: venv/bin/pip install -r misc/requirements.txt
      - run: PATH=$PWD/venv/bin:$PATH make -C testsuite/unitary_tests check
